require('configuration.general')
require('configuration.reloads')
require('configuration.commands')
require('configuration.functions')
require('configuration.keybinds')
require('configuration.options')